/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Kaa.ThriftDemo.Service.Thrift
{

  /// <summary>
  /// Structs can also be exceptions, if they are nasty.
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class InvalidOperation : TException, TBase
  {

    public int? WhatOp { get; set; }

    public string Why { get; set; }

    public InvalidOperation() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                WhatOp = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Why = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("InvalidOperation");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (WhatOp != null) {
          field.Name = "whatOp";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(WhatOp.Value);
          oprot.WriteFieldEnd();
        }
        if (Why != null) {
          field.Name = "why";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Why);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("InvalidOperation(");
      bool __first = true;
      if (WhatOp != null) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("WhatOp: ");
        __sb.Append(WhatOp);
      }
      if (Why != null) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Why: ");
        __sb.Append(Why);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
